In [16]:
import cv2
import dlib
import numpy as np
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [ ]:
face_detector = dlib.get_frontal_face_detector()
face_predictor = dlib.shape_predictor('/content/shape_predictor_68_face_landmarks.dat')

In [ ]:
img = cv2.imread('/content/fb2.jpg')
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


In [ ]:
xl = []
yl = []
faces = face_detector(img_gray)
my_face = face_predictor(img_gray,faces[0])
for i in range(68):
  x = my_face.part(i).x
  y = my_face.part(i).y
  xl.append(x)
  yl.append(y)


In [ ]:
import numpy as np
xn = np.array(xl)
yn = np.array(yl)
fn = np.hstack((xn,yn))
fn

array([206, 208, 212, 219, 235, 264, 301, 350, 409, 466, 511, 548, 572,
       583, 585, 585, 586, 235, 258, 298, 342, 382, 443, 477, 516, 549,
       569, 413, 415, 417, 420, 361, 387, 414, 437, 460, 278, 301, 328,
       352, 327, 300, 459, 485, 512, 533, 511, 485, 307, 341, 379, 409,
       439, 474, 499, 474, 438, 406, 375, 339, 317, 378, 408, 438, 488,
       438, 407, 377, 387, 435, 482, 532, 581, 624, 659, 688, 697, 685,
       655, 618, 577, 532, 485, 442, 398, 338, 304, 288, 286, 299, 307,
       295, 301, 318, 347, 349, 380, 410, 443, 467, 475, 484, 476, 469,
       366, 352, 352, 367, 373, 373, 373, 361, 363, 378, 383, 380, 532,
       513, 508, 515, 509, 519, 537, 564, 579, 582, 579, 564, 533, 524,
       528, 525, 536, 555, 559, 556])

In [ ]:
fnn = fn.reshape(1,136)
fnn.shape

(1, 136)

In [ ]:
lr.predict(fnn)

array([-0.18464977])

In [ ]:
pt = lr.predict(fnn)
yaw = lr1.predict(fnn)
o = lr2.predict(fnn)

In [ ]:
res = np.hstack((pt,yaw,o))

In [ ]:
res.shape

(3,)

In [4]:
from math import sin , cos
def draw_axis(img, pitch,yaw,roll, tdx=None, tdy=None, size = 100):

    yaw = -yaw
    if tdx != None and tdy != None:
        tdx = tdx
        tdy = tdy
    else:
        height, width = img.shape[:2]
        tdx = width / 2
        tdy = height / 2

    # X-Axis pointing to right. drawn in red
    x1 = size * (cos(yaw) * cos(roll)) + tdx
    y1 = size * (cos(pitch) * sin(roll) + cos(roll) * sin(pitch) * sin(yaw)) + tdy

    # Y-Axis | drawn in green
    #        v
    x2 = size * (-cos(yaw) * sin(roll)) + tdx
    y2 = size * (cos(pitch) * cos(roll) - sin(pitch) * sin(yaw) * sin(roll)) + tdy

    # Z-Axis (out of the screen) drawn in blue
    x3 = size * (sin(yaw)) + tdx
    y3 = size * (-cos(yaw) * sin(pitch)) + tdy

    cv2.line(img, (int(tdx), int(tdy)), (int(x1),int(y1)),(0,0,255),3)
    cv2.line(img, (int(tdx), int(tdy)), (int(x2),int(y2)),(0,255,0),3)
    cv2.line(img, (int(tdx), int(tdy)), (int(x3),int(y3)),(255,0,0),2)

    return img

In [ ]:
imgg = draw_axis(img,pt,yaw,o)

In [ ]:
cv2.imwrite('result.jpg',imgg)

True

In [6]:
!pip install mediapipe

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 32.8 MB 1.9 MB/s 


In [7]:
import mediapipe as mp

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [9]:
images_path = '/content/drive/MyDrive/jpeg'

In [12]:
import os
count = 0
ocount = 0
mesh = mp.solutions.face_mesh.FaceMesh(static_image_mode=True)
samples = []
imgs = os.listdir(images_path)
for i in imgs:
  ocount+=1
  print(ocount)
  print(images_path+'/'+i)
  im = cv2.imread(images_path+'/'+i)
  print(im.shape)
  imb = cv2.cvtColor(im,cv2.COLOR_BGR2RGB)
  ft = mesh.process(imb)
  lx=[]
  ly=[]
  # print((ft.multi_face_landmarks)[0].landmark[0])
  # break
  
  for j in range(468):
    if(ft.multi_face_landmarks) == None:
      break
    lx.append((ft.multi_face_landmarks)[0].landmark[j].x)
    ly.append((ft.multi_face_landmarks)[0].landmark[j].y)
    # print(j.landmark[0],j.landmark[0])
    count+=1
    # print(count)
  samples.append(np.hstack((np.array(lx),np.array(ly))))  
    


Streaming output truncated to the last 5000 lines.
/content/drive/MyDrive/jpeg/image02796.jpg
(450, 450, 3)
335
/content/drive/MyDrive/jpeg/image02782.jpg
(450, 450, 3)
336
/content/drive/MyDrive/jpeg/image02803.jpg
(450, 450, 3)
337
/content/drive/MyDrive/jpeg/image02781.jpg
(450, 450, 3)
338
/content/drive/MyDrive/jpeg/image02798.jpg
(450, 450, 3)
339
/content/drive/MyDrive/jpeg/image02792.jpg
(450, 450, 3)
340
/content/drive/MyDrive/jpeg/image02797.jpg
(450, 450, 3)
341
/content/drive/MyDrive/jpeg/image02804.jpg
(450, 450, 3)
342
/content/drive/MyDrive/jpeg/image02771.jpg
(450, 450, 3)
343
/content/drive/MyDrive/jpeg/image02788.jpg
(450, 450, 3)
344
/content/drive/MyDrive/jpeg/image02768.jpg
(450, 450, 3)
345
/content/drive/MyDrive/jpeg/image02790.jpg
(450, 450, 3)
346
/content/drive/MyDrive/jpeg/image02760.jpg
(450, 450, 3)
347
/content/drive/MyDrive/jpeg/image02763.jpg
(450, 450, 3)
348
/content/drive/MyDrive/jpeg/image02764.jpg
(450, 450, 3)
349
/content/drive/MyDrive/jpeg/image0

In [13]:
samples = np.array(samples)
samples[0].shape


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


(936,)

In [ ]:
samples[2]

array([0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473017,
       0.49473017, 0.49473017, 0.49473017, 0.49473017, 0.49473

In [14]:
fin = np.zeros((2000,936,1))
print(fin[0].shape,samples[0].shape)
cc = 0
for z in range(2000):
  if(samples[z]).size == 0:
    continue
  cc+=1
  print(cc)
  fin[z] = samples[z].reshape((936,1))


(936, 1) (936,)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273


In [15]:
fin.shape

(2000, 936, 1)

In [17]:
linr1 = SVR()
linr2 = SVR()
linr3 = SVR()

In [19]:
import pickle as pk
lolo = open('/content/feat.pickle',"rb")
examp = pk.load(lolo)
p = examp[0:,136]
yaw = examp[0:,137]
roll = examp[0:,138]

In [20]:
linr1.fit(fin.reshape(2000,936),p.reshape(2000,1))
from sklearn.metrics import r2_score
r2_score(p.reshape(2000,1),linr1.predict(fin.reshape(2000,936)))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0

In [21]:
linr2.fit(fin.reshape(2000,936),yaw.reshape(2000,1))
r2_score(yaw.reshape(2000,1),linr2.predict(fin.reshape(2000,936)))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0

In [23]:
xpitch_train , xpitch_test , ypitch_train , ypitch_test = train_test_split(fin.reshape(2000,936),p.reshape(2000,1),test_size=0.2,random_state=42)
lir1 = SVR()
lir1.fit(xpitch_train,ypitch_train)
r2_score(ypitch_test,lir1.predict(xpitch_test))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0

In [24]:
xyaw_train , xyaw_test , yyaw_train , yyaw_test = train_test_split(fin.reshape(2000,936),yaw.reshape(2000,1),test_size=0.2,random_state=42)
lir2 = SVR()
lir2.fit(xyaw_train,yyaw_train)
r2_score(yyaw_test,lir2.predict(xyaw_test))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0

In [25]:
xroll_train , xroll_test , yroll_train , yroll_test = train_test_split(fin.reshape(2000,936),roll.reshape(2000,1),test_size=0.2,random_state=42)
lir3 = SVR()
lir3.fit(xroll_train,yroll_train)
r2_score(yroll_test,lir3.predict(xroll_test))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0

In [26]:
my_sample = []
klx = []
kly = []
mine = cv2.imread('/content/fb2.jpg')
mine = cv2.cvtColor(mine,cv2.COLOR_BGR2RGB)
kft = mesh.process(mine)
for k in range(468):
    if(kft.multi_face_landmarks) == None:
      break
    klx.append((kft.multi_face_landmarks)[0].landmark[k].x)
    kly.append((kft.multi_face_landmarks)[0].landmark[k].y)
    # print(j.landmark[0],j.landmark[0])
    count+=1
    # print(count)
my_sample.append(np.hstack((np.array(klx),np.array(kly))))  

In [27]:
minee = np.array(my_sample)

In [28]:
ppitch = lir1.predict(minee)
pyaw = lir2.predict(minee)
proll = lir3.predict(minee)

In [29]:
reso = draw_axis(mine,ppitch,pyaw,proll,size=300)
cv2.imwrite('resoo2.jpg',reso)

True

In [ ]:
mine.shape

(960, 959, 3)